### ISSUE TITLE
FIXME/TODO Count 17

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-profile-http#15]
- [ ] FIXME set this to false once we have
       Commit: (3762e25) Start validators for all endpoints.
       File:  [schemas/bedrock-profile-http.js:80](https://github.com/digitalbazaar/bedrock-profile-http/blob/master/schemas/bedrock-profile-http.js#L80)
       Andrew L Jones commented 2 months ago

  - [ ] FIXME set this to false if we
       Commit: (3762e25) Start validators for all endpoints.
       File:  [schemas/bedrock-profile-http.js:60](https://github.com/digitalbazaar/bedrock-profile-http/blob/master/schemas/bedrock-profile-http.js#L60)
       Andrew L Jones commented 2 months ago

  - [ ] FIXME set this to false once we have
       Commit: (3762e25) Start validators for all endpoints.
       File:  [schemas/bedrock-profile-http.js:47](https://github.com/digitalbazaar/bedrock-profile-http/blob/master/schemas/bedrock-profile-http.js#L47)
       Andrew L Jones commented 2 months ago

  - [ ] FIXME set this to false once we have
       Commit: (3762e25) Start validators for all endpoints.
       File:  [schemas/bedrock-profile-http.js:31](https://github.com/digitalbazaar/bedrock-profile-http/blob/master/schemas/bedrock-profile-http.js#L31)
       Andrew L Jones commented 2 months ago

  - [ ] FIXME set this to false once we have
       Commit: (3762e25) Start validators for all endpoints.
       File:  [schemas/bedrock-profile-http.js:21](https://github.com/digitalbazaar/bedrock-profile-http/blob/master/schemas/bedrock-profile-http.js#L21)
       Andrew L Jones commented 2 months ago

  - [ ] // TODO: Add permissions to allow access for admin
       Commit: (d9a9bbe) Rework HTTP API with new br-profile API.
       File:  [lib/http.js:281](https://github.com/digitalbazaar/bedrock-profile-http/blob/master/lib/http.js#L281)
       Ganesh Annan commented 3 months ago

  - [ ] TODO: Implement claim profile agent
       Commit: (d9a9bbe) Rework HTTP API with new br-profile API.
       File:  [lib/http.js:267](https://github.com/digitalbazaar/bedrock-profile-http/blob/master/lib/http.js#L267)
       Ganesh Annan commented 3 months ago

  - [ ] TODO: Add permissions to allow access for admin
       Commit: (d9a9bbe) Rework HTTP API with new br-profile API.
       File:  [lib/http.js:248](https://github.com/digitalbazaar/bedrock-profile-http/blob/master/lib/http.js#L248)
       Ganesh Annan commented 3 months ago

  - [ ] TODO: Add permissions to allow access for admin
       Commit: (d9a9bbe) Rework HTTP API with new br-profile API.
       File:  [lib/http.js:209](https://github.com/digitalbazaar/bedrock-profile-http/blob/master/lib/http.js#L209)
       Ganesh Annan commented 3 months ago

  - [ ] TODO: Add permissions to allow access for admin
       Commit: (655a6d4) Implement delete profile agent.
       File:  [lib/http.js:145](https://github.com/digitalbazaar/bedrock-profile-http/blob/master/lib/http.js#L145)
       Ganesh Annan commented 3 months ago

  - [ ] FIXME: Use http-sigs and zcaps for
       Commit: (655a6d4) Implement delete profile agent.
       File:  [lib/http.js:144](https://github.com/digitalbazaar/bedrock-profile-http/blob/master/lib/http.js#L144)
       Ganesh Annan commented 3 months ago

  - [ ] TODO: Add permissions to allow access for admin
       Commit: (d9a9bbe) Rework HTTP API with new br-profile API.
       File:  [lib/http.js:124](https://github.com/digitalbazaar/bedrock-profile-http/blob/master/lib/http.js#L124)
       Ganesh Annan commented 3 months ago

  - [ ] FIXME: Use http-sigs and zcaps for
       Commit: (655a6d4) Implement delete profile agent.
       File:  [lib/http.js:123](https://github.com/digitalbazaar/bedrock-profile-http/blob/master/lib/http.js#L123)
       Ganesh Annan commented 3 months ago

  - [ ] TODO: Add permissions to allow access for admin
       Commit: (d9a9bbe) Rework HTTP API with new br-profile API.
       File:  [lib/http.js:96](https://github.com/digitalbazaar/bedrock-profile-http/blob/master/lib/http.js#L96)
       Ganesh Annan commented 3 months ago

  - [ ] TODO: Add permissions to allow access for admin
       Commit: (4238048) Add support for token in profileAgent.
       File:  [lib/http.js:66](https://github.com/digitalbazaar/bedrock-profile-http/blob/master/lib/http.js#L66)
       Matthew Collier commented 2 months ago

  - [ ] TODO: Add permissions to allow access for admin
       Commit: (d9a9bbe) Rework HTTP API with new br-profile API.
       File:  [lib/http.js:44](https://github.com/digitalbazaar/bedrock-profile-http/blob/master/lib/http.js#L44)
       Ganesh Annan commented 3 months ago

  - [ ] FIXME: had to enable admin rights to create keyStore
       Commit: (38f5deb) Add initial implementation.
       File:  [test/mocha/mock.data.js:23](https://github.com/digitalbazaar/bedrock-profile-http/blob/master/test/mocha/mock.data.js#L23)
       Ganesh Annan commented 4 months ago

**Comment by dlongley** [comment]
Closing -- these have been transferred to issues or dealt with.
